### ISSUE TITLE
Plots are not shown since server update

### ISSUE THREAD

**Issue by terbed** [allegroai/clearml-server#262] opened 2024-11-06 10:33 UTC
I've updated my self-hosted clearml server to `WebApp: 1.16.2-502 • Server: 1.16.2-502 • API: 2.30` following the documentation guidelines. Unfortunately, since then, the plots page has not been working properly. Debug samples do work. For example:
<img width="655" alt="Screenshot 2024-11-06 at 11 30 40" src="https://github.com/user-attachments/assets/e2a8c42c-5fca-4b2a-b70f-d332d8b7a595">
<img width="997" alt="Screenshot 2024-11-06 at 11 30 52" src="https://github.com/user-attachments/assets/96f7118d-37d8-417e-998c-15cd6d7108fd">

I've uploaded the exact figure as a debug sample, and as a plot, but in case the former is not shown.

**Comment by shyallegro** [comment] 2024-11-07 07:34
Duplicate of #248

**Closed as completed** 2024-11-07 08:41 UTC
