### ISSUE TITLE
[Bug / UI] Path to project breaks after refresh

### ISSUE THREAD

**Issue by juhoarjo** [allegroai/clearml-server#142] opened 2022-05-24 08:54 UTC
Refreshing the page on the Projects view breaks the path to project on the top left corner of the view if the path is long.

**Comment by ainoam** [comment] 2022-05-24 09:42
Thanks for the report @juhoarjo. Before/After refresh screenshots would help pinpoint and fix the issue.

**Comment by juhoarjo** [comment] 2022-05-24 10:00
After testing it a bit more I'm not so sure it relates to the length of the path. Here are the requested screenshots.
![Screenshot 2022-05-24 at 12 57 13](https://user-images.githubusercontent.com/88322506/170005502-2e7dab4c-fc3d-4356-a6cc-16bac37aaa0b.png)
![Screenshot 2022-05-24 at 12 59 00](https://user-images.githubusercontent.com/88322506/170005509-3e429b9c-02cb-4315-92e4-e7f6602616d3.png)

**Comment by ainoam** [comment] 2022-05-24 10:19
Thanks for the screenshots @juhoarjo . Which server version have you encountered this on?
(Find the version at the bottom of the UI settings pages)

**Comment by DavidNativ** [comment] 2022-06-07 07:06
Hi 
I can't manage to reproduce your issue. Are you doing other things than creating the project and refresh the page ? 
_After testing it a bit more I'm not so sure it relates to the length of the path. Here are the requested screenshots._ 
Maybe you could share with me your thoughts here ?

Thanks

**Comment by idantene** [comment] 2022-06-07 07:19
I also experience this issue; there's not much I can add to @juhoarjo's description.
Pretty much the following:
1. Open a task or a project
2. Refresh the page
3. If the project path is gone -> success, the issue is reproduced
4. If the project path is still there, return to step 2 (seems to happen most of the time, but not consistently)

It seems that the entire project path is loaded dynamically and potentially sometimes fails (or at least does not update the UI)

**Comment by juhoarjo** [comment] 2022-06-07 07:19
I can reproduce the issue by creating a new project or selecting an existing one and then just refreshing the page. There can be experiments within the project or not - that does not seem to matter. It can already happen on the /bugtest/path level on the previous examples with the screenshots. Any refresh seems to trigger this.

**Comment by pollfly** [comment] 2022-10-25 11:05
Hey @juhoarjo! Just letting you know that this issue has been resolved in the recently released [v1.6.0](https://github.com/allegroai/clearml-server/releases/tag/v1.6.0). Let us know if there are any issues :)

**Comment by jkhenning** [comment] 2023-03-15 13:06
Closing this issue. Please reopen if it's still relevant.

**Closed by jkhenning** 2023-03-15 13:06 UTC
