### ISSUE TITLE
Mismatch between Dockerfile and docker image in Dockerhub

### ISSUE THREAD

**Issue by Hartorn** [allegroai/clearml-server#135] opened 2022-04-29 14:15 UTC
Hi,
I'm using ClearML, and as I wanted to patch some log level and info into the entrypoint, I realised that the Dockerfile in the github repository and the one in the image in dockerhub is not the same
See both below : 
https://hub.docker.com/layers/allegroai/clearml/1.4.0/images/sha256-e1ffbcb6baa8c23285f9ab183b22296d1d9c443383bc2b3206ce0e5878c3227b?context=explore

https://github.com/allegroai/clearml-server/blob/master/docker/build/Dockerfile

We can see in one case the file is name `wrapper.sh`, in the other `entrypoint.sh`
So I would like to understand what we are using when pulling from dockerhub, and how different it is from building it from source.
Also, is the Jenkins CI building the image from the repo accessible ?

Thanks :)
Cheers !

**Comment by jkhenning** [comment] 2022-05-03 20:24
Hi @Hartorn!

Sorry for taking so long to respond 🙂 

The dockerfile we use to build the released versions of ClearML Server is indeed different from the one in the public repository, since we do that as part of our internal CI/CD and use a longer automated process which is also tested internally before pushed to the official dockerhub repository. For that reason, we still can't share the Jenkins CI building this as it simply won't work... We will however be more than happy for such a contribution for the github repo 😉

**Comment by zandolsi-psee** [comment] 2022-07-12 14:42
Hi @jkhenning,
Indeed, I made a PR in order to make changes. When I saw that it was merged, I wanted to use the public image and I discover that my modifications were not included. By comparing the source code and the image on docker hub I discover that they are different. I understand you don't want to share your CI/CD process however it should point to the public source code.

**Comment by jkhenning** [comment] 2022-07-12 15:32
Hi @zandolsi-psee,

Since we release lots of flavors of the ClearML Server and release images only after testing and regression, we do need our internal CI/CD process to use different internal Dockerfile files.
Having said that, we usually do make sure we merge suggested changes to our Dockerfiles as well (can you perhaps point me to the specific merge you're talking about?).
Of course, since the code in the GitHub repository always reflects the last server release, we would welcome having a GitHub-powered build process on-commit, and would welcome a PR to help us do that (I assume this can fairly easily be done using the GitHub CI/CD and the image can be hosted in the GitHub container registry) 🙂

**Comment by zandolsi-psee** [comment] 2022-07-12 15:51
For example, this one : https://github.com/allegroai/clearml-server/pull/121

**Comment by zandolsi-psee** [comment] 2022-08-26 08:38
Hi @jkhenning,
Do you have any idea when this PR will be in the official image ?

**Comment by shyallegro** [comment] 2022-09-01 15:30
Hi @zandolsi-psee,
sorry for the delay, I'll make sure to take care of this before the next release.

**Comment by pollfly** [comment] 2022-10-27 09:51
Hey @Hartorn! [v1.7.0](https://github.com/allegroai/clearml-server/releases/tag/v1.7.0) is now out supporting serving the UI from a non-root path of the ClearML Server.

**Comment by jkhenning** [comment] 2023-03-15 13:07
Closing this issue. Please reopen if it's still relevant.

**Closed by jkhenning** 2023-03-15 13:07 UTC
